"""add follow table

Revision ID: 59f95058cf49
Revises: 029fc3ea35f1
Create Date: 2025-04-27 19:09:33.452528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f95058cf49'
down_revision = '029fc3ea35f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='_follower_followed_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
